services:
  nginx-css:
    image: nginx:latest
    container_name: nginx-css
    volumes:
      - ./Natours:/usr/share/nginx/html/Natours
      - ./Trillo:/usr/share/nginx/html/Trillo
      - ./Nexter:/usr/share/nginx/html/Nexter
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-css.rule=Host(`css.${DOMAIN}`)
      - traefik.http.services.nginx-css.loadbalancer.server.port=80
      - traefik.http.routers.nginx-css.entrypoints=websecure
      - traefik.http.routers.nginx-css.tls=true
      - traefik.http.routers.nginx-css.tls.certresolver=cloudflare
      - traefik.http.routers.nginx-css.service=nginx-css

networks:
  traefik-net:
    external: true