services:
  nginx:
    image: docker.io/library/nginx:1.27.4-alpine
    container_name: trillo
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data:/usr/share/nginx/html:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.trillo.rule=Host(`trillo.${DOMAIN}`)
      - traefik.http.services.trillo.loadbalancer.server.port=80
      - traefik.http.routers.trillo.entrypoints=websecure
      - traefik.http.routers.trillo.tls=true
      - traefik.http.routers.trillo.tls.certresolver=cloudflare
      - traefik.http.routers.trillo.service=trillo
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true
